#pull data from k8s secrets or configMap set in Deployment, Pod etc
secretKey: SECRET_KEY
firebase:
  document: FIREBASE_DOCUMENT
  serviceKey:
    type: FIREBASE_SERVICE_ACCOUNT
    project_id: FIREBASE_PROJECT_ID
    private_key_id: FIREBASE_PRIVATE_KEY_ID
    private_key: FIREBASE_PRIVATE_KEY
    client_email: FIREBASE_CLIENT_EMAIL
    client_id: FIREBASE_CLIENT_ID
    client_x509_cert_url: FIREBASE_CLIENT_CERT_URL
    auth_uri: FIREBASE_AUTH_URI
    token_uri: FIREBASE_TOKEN_URI
    auth_provider_x509_cert_url: FIREBASE_PROVIDER_CERT_URL